version: "3.9"

services:
  api:
    build: .
    container_name: caspino-api
    restart: unless-stopped
    command: ["node", "--loader", "ts-node/esm", "src/index.ts"]
    ports:
      - "5500:5500"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      BASETEN_API_KEY: ${BASETEN_API_KEY}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  roulette:
    build: .
    container_name: caspino-roulette
    restart: unless-stopped
    command: ["node", "--loader", "ts-node/esm", "src/games/roulette/index.ts"]
    ports:
      - "5600:5600"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  slots:
    build: .
    container_name: caspino-slots
    restart: unless-stopped
    command: ["node", "--loader", "ts-node/esm", "src/games/slots/index.ts"]
    ports:
      - "5700:5700"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  blackjack:
    build: .
    container_name: caspino-blackjack
    restart: unless-stopped
    command: ["node", "--loader", "ts-node/esm", "src/games/blackjack/index.ts"]
    ports:
      - "5800:5800"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
